services:
  api:
    build:
      context: ./backend
    environment:
      - PORT=5050
      - FRONTEND_ORIGIN=http://localhost:8080
    ports:
      - "5050:5050"

  web:
    build:
      context: ./frontend/frontendApp
    depends_on:
      - api
    ports:
      - "8080:80"
